import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import three from "../../../assets/3d art.png";
import { useAIPrompt } from "../store/hooks";
import { useParams } from "react-router-dom";
import { Skeleton } from "@/components/ui/skeleton";

const AnatomyDashboard = () => {
  const { id } = useParams();
  const { data, isLoading, isSuccess } = useAIPrompt(id);
  return (
    // <div className="h-screen w-full bg-slate-50 p-4">
    //   <div className="relative h-full w-full">
    //     {/* Center Figure */}
    //     {/* <div className="absolute inset-0 flex items-center justify-center">
    //       <img
    //         src={three}
    //         alt="Human Anatomy"
    //         className="h-[72] object-contain"
    //       />
    //     </div> */}

    //     {/* Corner Cards Container */}
    //     {/* <div className="absolute inset-0 p-6">
    //       <div className="relative h-full w-full"> */}
    //         {/* Top Left */}

    //         <Card>
    //           <CardHeader className="p-2">
    //             <CardTitle className="text-sm">
    //               According the profile of the students what are the career that
    //               he can persue in future.?{" "}
    //               <span className="text-xs text-slate-400">
    //                 Generated by Gemini
    //               </span>
    //             </CardTitle>
    //           </CardHeader>
    //           <CardContent className="p-2 pt-0">
    //             <ul className="text-xs space-y-1">
    //               <li>Medical Doctor</li>
    //               <li>Physical Therapist</li>
    //               <li>Sports Medicine</li>
    //             </ul>
    //           </CardContent>
    //         </Card>

    //       </div>
    //     </div>
    //   </div>
    // </div>
    <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-0 mt-3">
      {isLoading && (
        <Card className="w-full">
          <CardHeader>
            <CardTitle>
              <Skeleton className="h-6 w-32" /> {/* Simulates the title */}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {/* Skeleton lines simulating content */}
            <Skeleton className="h-4 w-3/4 mb-2" />
            <Skeleton className="h-4 w-2/3 mb-2" />
            <Skeleton className="h-4 w-1/2" />
          </CardContent>
        </Card>
      )}
      {!isLoading && data?.data.length > 0
        ? data?.data.map((ai) => (
            <Card className="w-full" key={ai.id}>
              <CardHeader>
                <CardTitle>{ai.prompt}</CardTitle>
              </CardHeader>
              <CardContent>
                {typeof ai.result === "object"
                  ? JSON.stringify(ai.result, null, 2)
                  : ai.result}
              </CardContent>
            </Card>
          ))
        : null}
    </main>
  );
};

export default AnatomyDashboard;
