import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import three from "../../../assets/3d art.png";

const AnatomyDashboard = () => {
  return (
    <div className="h-screen w-full bg-slate-50 p-4">
      <div className="relative h-full w-full">
        {/* Center Figure */}
        <div className="absolute inset-0 flex items-center justify-center">
          <img
            src={three}
            alt="Human Anatomy"
            className="h-[72] object-contain"
          />
        </div>

        {/* Corner Cards Container */}
        <div className="absolute inset-0 p-6">
          <div className="relative h-full w-full">
            {/* Top Left */}
            <Card className="absolute top-0 left-0 w-48 shadow-none border border-gray-300">
              <CardHeader className="p-2">
                <CardTitle className="text-sm">According the profile of the students what are the career that he can persue in future.? <span className="text-xs text-slate-400">Generated by Gemini</span></CardTitle>
              </CardHeader>
              <CardContent className="p-2 pt-0">
                <ul className="text-xs space-y-1">
                  <li>Medical Doctor</li>
                  <li>Physical Therapist</li>
                  <li>Sports Medicine</li>
                </ul>
              </CardContent>
            </Card>

            {/* Top Right */}
            <Card className="absolute top-0 right-0 w-48 shadow-none border border-gray-300">
              <CardHeader className="p-2">
                <CardTitle className="text-sm">According to his physical what are the sports that he can participate.</CardTitle>
              </CardHeader>
              <CardContent className="p-2 pt-0">
                <ul className="text-xs space-y-1">
                  <li>Stress Management</li>
                  <li>Work-Life Balance</li>
                  <li>Mindfulness</li>
                </ul>
              </CardContent>
            </Card>

            {/* Bottom Left */}
            <Card className="absolute bottom-0 left-0 w-48 shadow-none border border-gray-300">
              <CardHeader className="p-2">
                <CardTitle className="text-sm">
                  Institute Opportunities
                </CardTitle>
              </CardHeader>
              <CardContent className="p-2 pt-0">
                <ul className="text-xs space-y-1">
                  <li>Research Programs</li>
                  <li>Training Courses</li>
                  <li>Certifications</li>
                </ul>
              </CardContent>
            </Card>

            {/* Bottom Right */}
            <Card className="absolute bottom-0 right-0 w-48 shadow-none border border-gray-300">
              <CardHeader className="p-2">
                <CardTitle className="text-sm">Physical Health</CardTitle>
              </CardHeader>
              <CardContent className="p-2 pt-0">
                <ul className="text-xs space-y-1">
                  <li>Exercise Guidelines</li>
                  <li>Nutrition Tips</li>
                  <li>Wellness Programs</li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnatomyDashboard;
